# .travis.yml
language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
services: postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec test
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database monocle_test' -U postgres
