source 'https://rubygems.org'
gem 'chartkick'
gem 'devise'
gem 'groupdate'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'pg'
gem 'rails', '4.1.0'
gem 'spring',        group: :development
gem 'turbolinks'